server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db?stringtype=unspecified
    username: postgres
    password: pushkar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        show:
          sql: true
  jackson:
    default-property-inclusion: null
