server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_db?stringtype=unspecified
    username: postgres
    password: pushkar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        show:
          sql: true
  jackson:
    default-property-inclusion: null

  application:
    name: USER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka