server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rating_db?stringtype=unspecified
    username: postgres
    password: pushkar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        show:
          sql: true